orzyyyy/memo

- package-lock.json
- package.json
- server/controller/DocumentController.ts
- server/service/DocumentService.ts
- src/controller/MarkdownEditorDataController.tsx
- src/pages/MarkdownEditor.tsx
>  feat: support to format markdown content by prettier

- src/controller/MainPageDataController.tsx
- src/pages/ExHentaiList.tsx
- src/pages/MainPage.tsx
- src/pages/__tests__/__snapshots__/MainPage.test.js.snap
To close https://github.com/orzyyyy/memo/issues/84
> feat: download target images by input url

- server/controller/ExhentaiController.ts
- server/resource/server.toml
- server/service/ExhentaiService.ts
- server/utils/exhentai.ts
- 修改时间间隔为 1000 ms
- 增加 `/download/target` 以重新下载具体图片路径
- 增加 `/download/stat`以检查遗漏图片信息
- 修改浏览器启动设置 `devtools` => `headless`
> feat(exhentai): check url of detail images when failed

- package.json
Related to https://github.com/ant-design/ant-design/issues/17928
> test: pinned css-animation to fix crash

- package.json
- src/assets/mapping.json
- src/controller/MainPageDataController.tsx
- src/pages/EditForm.tsx
- src/pages/MainPageHeader.tsx
- src/pages/MainPageList.tsx
- src/pages/__tests__/EditForm.test.js
- src/pages/__tests__/__snapshots__/EditForm.test.js.snap
- src/pages/__tests__/__snapshots__/MainPageHeader.test.js.snap
- src/pages/__tests__/__snapshots__/MainPageList.test.js.snap
Form: 使用新 api
Icon: 引用 `@ant-design/icons` 和 `@ant-design/icons-svg` 替换原有引用方式，以便 tree-shaking
close https://github.com/orzyyyy/memo/issues/163
> refactor: Form and Icon

- server/controller/ExhentaiController.ts
- server/utils/exhentai.ts
- src/controller/ExHentaiListDataController.tsx
- src/controller/MainPageDataController.tsx
- src/pages/ExHentaiList.tsx
- src/pages/MainPage.tsx
- src/pages/MainPageHeader.tsx
- src/pages/__tests__/MainPage.test.js
- src/pages/__tests__/MainPageHeader.test.js
- src/pages/__tests__/__snapshots__/ExHentaiList.test.js.snap
- src/pages/__tests__/__snapshots__/MainPageHeader.test.js.snap
> feat: assign target datestamp for exhentai list

- package.json
Related to https://github.com/ant-design/ant-design-icons/issues/99
> fix: warning from ant-design-icons

- server/controller/DocumentController.ts
- server/controller/ExhentaiController.ts
- server/service/DocumentService.ts
- server/utils/document.ts
F5 爬完列表，直接访问 list 会 404。list 只会写入 src/assets，所以需要把 info 写入 dist
>  feat(exhentai): update list info in dist

- server/controller/ExhentaiController.ts
- server/resource/server.toml
- server/service/ExhentaiService.ts
- server/utils/log.ts
> feat(exhentai): re-initiate request after failed for list

- server/controller/ExhentaiController.ts
- server/service/ExhentaiService.ts
> feat(exhentai): re-initiate request for preparing download after failed

- package.json
Related to https://github.com/orzyyyy/nino-cli/commit/a464bb21dcf3da8eb671a8f01231b4bd6185cd5a
Close #205
> feat: simulated offline status

- server/utils/document.ts
- src/assets/mapping.json
- src/assets/sider.json
- src/controller/MainPageDataController.tsx
> feat: hide target mappings

- nino.koei.js
> perf: uglify json files

- CHANGELOG.md
- package.json
-----
[View rendered CHANGELOG.md](https://github.com/orzyyyy/memo/blob/release/CHANGELOG.md)
> chore: bump 1.1.1

- src/controller/ExHentaiListDataController.tsx
- src/controller/MainPageDataController.tsx
- src/controller/__tests__/MainPageDataController.test.js
> perf(exhentai): add feedback for download

- src/controller/__tests__/__snapshots__/MappingDetailDataController.test.tsx.snap
- src/pages/MainPageList.tsx
- src/pages/__tests__/__snapshots__/MappingDetail.test.tsx.snap
> perf: tweak fade animation of dialog

- CHANGELOG.md
- package.json
-----
[View rendered CHANGELOG.md](https://github.com/orzyyyy/memo/blob/release/CHANGELOG.md)
> chore: bump 1.1.2

- src/component/LineNumber.tsx
- src/controller/MarkdownEditorDataController.tsx
- src/controller/__tests__/__snapshots__/MarkdownEditorDataController.test.tsx.snap
- src/pages/MarkdownEditor.tsx
- src/pages/__tests__/__snapshots__/MarkdownEditor.test.tsx.snap
- src/pages/css/MarkdownEditor.css
> chore: init with component LineNumber

- scripts/utils.js
- src/assets/sider.json
- src/controller/MainPageDataController.tsx
- src/pages/UtilList.tsx
- src/pages/css/MainPage.css
> chore: init for util list

- scripts/utils.js
- src/assets/rightBar.json
- src/controller/MainPageDataController.tsx
- src/pages/MainPageList.tsx
- src/router/index.tsx
> feat: add url nav

- src/component/Upload/UploadView.tsx
- src/component/Upload/Uploader.tsx
- src/component/Upload/__tests__/Upload.test.tsx
- src/component/Upload/__tests__/__snapshots__/Upload.test.tsx.snap
- src/pages/SlicingImage.tsx
> feat: add prop uploaderVisible for UploadView

- src/component/Upload/UploadView.tsx
- src/component/Upload/Uploader.tsx
- src/component/Upload/__tests__/__snapshots__/Upload.test.tsx.snap
- src/pages/SlicingImage.tsx
- src/pages/css/slicing-image.css
> feat: slice image

- .github/workflows/deploy.yml
- src/controller/MainPageDataController.tsx
> fix: pathname of gh-pages crashed when clicking list item

- src/assets/mapping.json
- src/assets/markdown/5652a52ab188e25bddf687b32d4ce326.md
-----
[View rendered src/assets/markdown/5652a52ab188e25bddf687b32d4ce326.md](https://github.com/orzyyyy/memo/blob/config/src/assets/markdown/5652a52ab188e25bddf687b32d4ce326.md)
> docs: update config after install

- src/controller/MainPageDataController.tsx
- src/pages/EditForm.tsx
Use history.push instead of history.replace.
> perf: improve back event
